'use strict';

// tests for getProductById
// Generated by serverless-jest-plugin

const mod = require('../import-products-file/import-products-file');
const jestPlugin = require('serverless-jest-plugin');
const lambdaWrapper = jestPlugin.lambdaWrapper;
const wrapped = lambdaWrapper.wrap(mod, { handler: 'importProductsFile' } );
const AWS = require('aws-sdk-mock');

const event = {
    queryStringParameters: {
        name: 'products.csv'
    }
}

describe('importProductsFile', () => {

    it('should get signedUrl from s3', () => {
        return wrapped.run(event).then(response => {
            const signedUrl = JSON.parse(response.body).split('?')[0];
            const fileNameFromSignedUrl = signedUrl.split('/')[signedUrl.split('/').length-1];

            expect(response.statusCode).toBe('200');
            expect(fileNameFromSignedUrl).toEqual(event.queryStringParameters.name);
        });
    });

    it('should return error if there is no йгукн parameter', () => {
        event.queryStringParameters = '';
        return wrapped.run(event).catch(error => {
            expect(error.statusCode).toBe('400');
            expect(error.body).toEqual(JSON.stringify({"message": "Query param not found!"}));
        });
    });
});
