service: products-service

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  profile: personalAccount

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

functions:
  getProducts:
    handler: products/products.getProducts
    events:
      - http:
          path: /products
          method: get
          cors: true
  getProductById:
    handler: product-by-id/product-by-id.getProductById
    events:
      - http:
          path: /product/{id}
          method: GET
          cors: true

