service: cart-service

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1
  profile: personalAccount

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
