'use strict';

// tests for getProducts
// Generated by serverless-jest-plugin

const data = require('../data.json');
const mod = require('./../products/products');
const jestPlugin = require('serverless-jest-plugin');

const lambdaWrapper = jestPlugin.lambdaWrapper;
const wrapped = lambdaWrapper.wrap(mod, { handler: 'getProducts' });

describe('getProducts', () => {
  beforeAll((done) => {
    done();
  });

  it('should return correct list of products', () => {
    return wrapped.run().then((response) => {
      expect(response.statusCode).toBe('200');
      expect(response.body).toEqual(JSON.stringify(data));
    });
  });
});
